Traceback (most recent call last):
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sfgary/sl_core/pca.py", line 110, in <module>
    predict_all.pop(predict_var),
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/site-packages/pandas/core/frame.py", line 5685, in pop
    return super().pop(item=item)
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/site-packages/pandas/core/generic.py", line 923, in pop
    result = self[item]
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sfgary/.miniconda3/envs/superlearner/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment'
